### ISSUE TITLE
Waves website improvements proposal - Roadmap information

### ISSUE THREAD

**Issue by travek** [wavesplatform/wavesplatform.com#111]
Dear Team!

I kindly ask you to think about addition of the Roadmap section to the main Waves web site.
Clear presentation of the roadmap will bring additional value to the platform, transparency on its development. Please consider to focus not only on short term rodmap (2018) but also on mid term (2019) and beyond.

There several buplications made about smart contracts development on the platform, multi sigs, atomic swaps, etc. All of them can be put together on the roadmap with links on documentation (if any), video streams, pdf docs (if any). Take a look how Cardano platfrom is presenting it's roadmap - it is hightly appreaciated by community.

Going into details Waves community is interested about what features are on your radar right now, in what you are committed to invest and what are under analysis. It will be good to know about your plans on sharding, POS algorithm evelution and improvements, client features, security features (if any), side chanes/multi chains, and much more.

Personally from me it would be greate to add some analysis what will be ROI of Waves leasing after addition of turing complete smart contracts.

Many thans for considering my proposals!

**Comment by Tsiguleva** [comment]
Hi! We are planning to develop a site with broader functionality, a better structure and more information about everything we're doing. This will include a roadmap, of course. Thank you for your proposal and examples - we will take these into account.

**Comment by optate823** [comment]
Have &Orz += =+Waves 0.00X @Cost Send Waves Protocol Address to: now. For Receipt there of.
