### ISSUE TITLE
No link / submenu on https://wavesplatform.com/product

### ISSUE THREAD

**Issue by dailydimaz** [wavesplatform/wavesplatform.com#95]
i notice there is many link that not attachmed on https://wavesplatform.com/product

here is the link

https://wavesplatform.com/product/dex
https://wavesplatform.com/product/token-launcher
https://wavesplatform.com/product/wallet

Better if when someone hover 'product' menu there is submenu appear for Wallet, DEX, and Token launcher

**Comment by dailydimaz** [comment]
and this too
https://wavesplatform.com/developers/smart-contracts

**Comment by dailydimaz** [comment]
still no feedback regarding this issues?

**Comment by Tsiguleva** [comment]
You are absolutely right. It would be better to display a submenu when you hover over the product menu. We are planning to develop the site to build better functionality, with a clearer structure and information. We will take your suggestion into consideration as we update it.
